export const sampleMenuData = [
    { name: "クランチ", value: 0.06 },
    { name: "レッグリフトクランチ", value: 0.08 },
    { name: "スロークランチ", value: 0.1 },
    { name: "トゥタッチクランチ", value: 0.08 },
    { name: "レッグレイズ", value: 0.07 },
    { name: "フラッターキック", value: 0.09 },
    { name: "ニートゥチェスト", value: 0.06 },
    { name: "ツイストクランチ", value: 0.08 },
    { name: "ツイストレッグレイズ", value: 0.1 },
    { name: "プランク", value: 0.06 },
    { name: "スクワット", value: 0.11 },
    { name: "ランジ", value: 0.11 },
    { name: "サイドランジ", value: 0.11 },
    { name: "ヒップリフト", value: 0.07 },
    { name: "カーフレイズ", value: 0.05 },
    { name: "縄跳び", value: 0.2 },
    { name: "ランニング", value: 0.18 },
    { name: "水泳", value: 0.16 },
    { name: "ウォーキング", value: 0.09 },
    { name: "サイクリング", value: 0.12 },
];